<a href="https://colab.research.google.com/github/harshitasingh4839/ML_practice/blob/main/MLR_model_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_diabetes
import pandas as pd
import numpy as np

In [20]:
X,y = load_diabetes(return_X_y=True)

In [21]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [22]:
X.shape

(442, 10)

In [23]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [24]:
y.shape

(442,)

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=4)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((353, 10), (89, 10), (353,), (89,))

In [27]:
from sklearn.linear_model import LinearRegression

In [28]:
lr = LinearRegression()

In [29]:
lr.fit(X_train,y_train)

LinearRegression()

In [30]:
y_pred = lr.predict(X_test)

In [31]:
lr.coef_

array([  33.40954056, -292.24112825,  481.08002807,  369.05716136,
       -966.32463944,  589.771093  ,  232.59825938,  288.32164654,
        802.69901575,   37.81345763])

In [32]:
lr.intercept_

151.1466544656964

In [33]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.46109889928420866

In [34]:
# Implementation of multiple linear regression

class MyLR:

  def __init__(self):
    self.intercept_ = None
    self.coef_ = None

  def fit(self,X_train,y_train):
    # To make first column of every row 1 to muktiply it with beta not(B0)
    X_train = np.insert(X_train,0,1,axis=1)

    # calculate the coeffs
    betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
    self.intercept_ = betas[0]
    self.coef_ = betas[1:]

  def predict(self,X_test):
    y_pred = np.dot(X_test,self.coef_)+ self.intercept_
    return y_pred




In [39]:
# create an object of the class
mlr = MyLR()

In [40]:
mlr.fit(X_train,y_train)

In [41]:
y_pred = mlr.predict(X_test)

In [42]:
r2_score(y_test,y_pred)

0.4610988992842088

In [43]:
mlr.coef_

array([  33.40954056, -292.24112825,  481.08002807,  369.05716136,
       -966.32463944,  589.771093  ,  232.59825938,  288.32164654,
        802.69901575,   37.81345763])

In [44]:
mlr.intercept_

151.14665446569646